spring:
  config:
    activate:
      on-profile: docker

  jackson:
    serialization:
      write-dates-as-timestamps: false
    deserialization:
      adjust-dates-to-context-time-zone: false
    modules:
      jsr310: true #Claude did that, thanks, good
    date-format: "iso" #also this one

  datasource:
    url: jdbc:postgresql://db:5432/codexlibris
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  data:
    redis:
      host: redis
      port: 6379
      timeout: 2000ms 

  cache:
    type: redis
    redis:
      time-to-live: 30m
      
  main:
    allow-bean-definition-overriding: true
    web-application-type: servlet
    
  mvc:
    converters:
      preferred-json-mapper: jackson

server:
  port: 8080
  forward-headers-strategy: framework

llm:
  api:
    url: http://llm:8001/recomender

springdoc:
  writer-with-default-pretty-printer: true
  default-produces-media-type: application/json
  swagger-ui:
    use-root-path: true
    url: /v3/api-docs

logging:
  level:
    org.springframework.boot.context.config: DEBUG
    org.springframework.boot.env: DEBUG
    org.springframework.data.redis: DEBUG
    com.codexlibris: DEBUG
    
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      probes:
        enabled: true
  metrics:
    tags:
      application: ${spring.application.name:codexlibris-api}
