spring:
  jackson:
    serialization:
      write-dates-as-timestamps: false
    deserialization:
      adjust-dates-to-context-time-zone: false
    modules:
      jsr310: true 
      
  config:
    activate:
      on-profile: dev

  application:
    name: codexlibris-api

  datasource:
    url: jdbc:postgresql://localhost:5432/codexlibris
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
    hikari:
      initialization-fail-timeout: 60000
      connection-timeout: 30000
      maximum-pool-size: 5
      minimum-idle: 1

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  data:
    redis:
      host: redis
      port: 6379
      timeout: 2000ms

  cache:
    type: redis
    redis:
      time-to-live: 30m

  main:
    allow-bean-definition-overriding: true
    web-application-type: servlet

server:
  port: 8080
  forward-headers-strategy: framework

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
    org.springframework.boot.context.config: DEBUG
    org.springframework.boot.env: DEBUG
    org.springframework.data.redis: DEBUG
    com.codexlibris: DEBUG

springdoc:
  writer-with-default-pretty-printer: true
  default-produces-media-type: application/json
  swagger-ui:
    use-root-path: true
    url: /v3/api-docs

llm:
  api:
    url: http://localhost:8001/recomender