spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/codexlibris
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 5
      minimum-idle: 1
      idle-timeout: 5000
      max-lifetime: 15000
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
