spring:
  datasource:
    url: jdbc:postgresql://db:5432/codexlibris
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    
  cache:
    type: redis
  
  redis:
    host: redis
    port: 6379
